# meta-camera-hub/recipes-connectivity/hostapd/files/hostapd.conf
interface=wlan0
driver=nl80211
ssid=montana_hub_net
hw_mode=g
channel=7

# Enable WMM (Required for N speeds)
wmm_enabled=1

# Enable 802.11n (Wi-Fi 4)
ieee80211n=1

# High Throughput Capabilities (Specific to Raspberry Pi)
# Enables Short Guard Interval (small speed boost) and 20MHz width
ht_capab=[SHORT-GI-20]

# (Optional: Use [HT40+] instead if you are in a remote area with no other Wi-Fi)

# TODO: change later? whitelist camera MACs
macaddr_acl=0
auth_algs=1
# TODO: changle later? SSID should not be visible
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=pickleman
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP