# meta-camera-hub/recipes-support/dnsmasq/files/dnsmasq.conf
interface=wlan0
dhcp-range=192.168.27.50,192.168.27.150,12h

# --- Static IP Reservations for Wyze Cams ---
# Camera 1
dhcp-host=80:48:2c:41:12:64,192.168.27.100

# Camera 2
dhcp-host=80:48:2c:41:0d:a1,192.168.27.101